pull_request_rules:
  - name: Automatic merge on label addition
    conditions:
      - -closed
      - label=mergify
      - check-success=Test
      - check-success=Helm
      - check-success=Kustomize
    actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: smart+fasttrack
  - name: Cleanup mergify tag on close
    conditions:
      - closed
      - label=mergify
    actions:
      delete_head_branch: {}
      label:
        remove: [mergify]
