
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-policy-v1beta1-eviction
  failurePolicy: Ignore
  name: vpodseviction.pod-graceful-drain.io
  rules:
  - apiGroups:
    - policy
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    resources:
    - pods/eviction
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-v1-pod
  failurePolicy: Ignore
  name: vpod.pod-graceful-drain.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - pods
  sideEffects: NoneOnDryRun
