apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - name: vpodseviction.pod-graceful-drain.io
    namespaceSelector:
      matchExpressions:
        - key: pod-graceful-drain
          operator: In
          values:
            - enabled
  - name: vpod.pod-graceful-drain.io
    namespaceSelector:
      matchExpressions:
        - key: pod-graceful-drain
          operator: In
          values:
            - enabled