{{/*
Assertions
*/}}
{{- with .Values.deleteAfter -}}
{{- $now := now -}}
{{- $seconds := sub ($now | dateModify . | unixEpoch) ($now | unixEpoch) -}}
{{- if or (gt $seconds 25) (lt $seconds 1) -}}
{{- fail (printf "'deleteAfter' should be >= 1s, <= 25s, current: %s" .) -}}
{{- end -}}
{{- end -}}
