apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pod-graceful-drain.fullname" . }}
  labels:
    {{- include "pod-graceful-drain.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pod-graceful-drain.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pod-graceful-drain.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pod-graceful-drain.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- with .Values.deleteAfter }}
            - --delete-after={{ . }}
            {{- end }}
            {{- if .Values.noDenyAdmission }}
            - --no-deny-admission
            {{- end }}
            {{- with .Values.logLevel }}
            - --log-level={{ . }}
            {{- end }}
            {{- if .Values.ignoreError }}
            - --ignore-error
            {{- end }}
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - containerPort: 8080
              name: metrics-server
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ template "pod-graceful-drain.fullname" . }}-cert