apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pod-graceful-drain.fullname" . }}
  labels:
    {{- include "pod-graceful-drain.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "pod-graceful-drain.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pod-graceful-drain.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{ toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pod-graceful-drain.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- with .Values.deleteAfter }}
            - --delete-after={{ . }}
            {{- end }}
            {{- if .Values.experimentalGeneralIngress }}
            - --experimental-general-ingress
            {{- end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel | quote }}

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: POD_SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName

          readinessProbe:
            httpGet:
              path: "/healthz"
              port: 9443
              scheme: HTTPS
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - containerPort: 8080
              name: metrics-server
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- with omit (.Values.affinity) "podAntiAffinity"  }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        podAntiAffinity:
          {{- if .Values.hardPodAntiAffinity }}
          {{- with omit ((.Values.affinity).podAntiAffinity) "requiredDuringSchedulingIgnoredDuringExecution"  }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- with ((.Values.affinity).podAntiAffinity).requiredDuringSchedulingIgnoredDuringExecution }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  {{- include "pod-graceful-drain.selectorLabels" . | nindent 18 }}
          {{- else }}
          {{- with omit ((.Values.affinity).podAntiAffinity) "preferredDuringSchedulingIgnoredDuringExecution"  }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- with ((.Values.affinity).podAntiAffinity).preferredDuringSchedulingIgnoredDuringExecution }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "pod-graceful-drain.selectorLabels" . | nindent 20 }}
          {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ template "pod-graceful-drain.fullname" . }}-cert
