{{- if semverCompare "<1.21-0" .Capabilities.KubeVersion.Version }}
apiVersion: policy/v1beta1
{{- else }}
apiVersion: policy/v1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "pod-graceful-drain.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "pod-graceful-drain.selectorLabels" . | nindent 6 }}
