apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pod-graceful-drain.fullname" . }}-role
  labels:
    {{- include "pod-graceful-drain.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch, patch, delete]
  - apiGroups: [""]
    resources: [services]
    verbs: [get, list, watch]
  - apiGroups: [elbv2.k8s.aws]
    resources: [targetgroupbindings]
    verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pod-graceful-drain.fullname" . }}-rolebinding
  labels:
    {{- include "pod-graceful-drain.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pod-graceful-drain.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "pod-graceful-drain.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
