apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pod-graceful-drain.fullname" . }}-role
  labels:
    {{- include "pod-graceful-drain.labels" . | nindent 4 }}
rules:
  - apiGroups: [ events.k8s.io ]
    resources: [ events ]
    verbs: [ create ]
  - apiGroups: [ "" ]
    resources: [ pods ]
    verbs: [ get, list, watch, patch, delete ]
  - apiGroups: [ "" ]
    resources: [ pods/eviction ]
    verbs: [ create ]
  - apiGroups: [ policy ]
    resources: [ poddisruptionbudgets ]
    verbs: [ get, list, watch ]
  - apiGroups: [ policy ]
    resources: [ poddisruptionbudgets/status ]
    verbs: [ update ]
  - apiGroups: [ "" ]
    resources: [ services ]
    verbs: [ get, list, watch ]
  - apiGroups: [ networking.k8s.io ]
    resources: [ ingresses ]
    verbs: [ list, watch ]
{{ if not .Values.experimentalGeneralIngress }}
  - apiGroups: [ elbv2.k8s.aws ]
    resources: [ targetgroupbindings ]
    verbs: [ list, watch ]
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pod-graceful-drain.fullname" . }}-rolebinding
  labels:
    {{- include "pod-graceful-drain.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pod-graceful-drain.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "pod-graceful-drain.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pod-graceful-drain.fullname" . }}-role
  labels:
    {{- include "pod-graceful-drain.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ secrets ]
    verbs: [ list, watch ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pod-graceful-drain.fullname" . }}-rolebinding
  labels:
    {{- include "pod-graceful-drain.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pod-graceful-drain.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "pod-graceful-drain.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
