name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-rust:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Rust components
        run: |
          rustup component add clippy
      - name: cargo fetch
        run: cargo fetch --verbose
      - id: fmt
        run: cargo fmt --check --all
        continue-on-error: true
      - id: check
        run: cargo check --frozen --workspace
        continue-on-error: true
      - id: clippy
        run: cargo clippy --frozen -- -D warnings
        continue-on-error: true
      - if: |
          steps.fmt.outcome != 'success' ||
          steps.check.outcome != 'success' ||
          steps.clippy.outcome != 'success'
        run: |
          echo "Something failed"
          exit 1

  check-python:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - run: |
          uv format --check --diff
        if: always()

  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind_image:
          - "v1.35.1"
          - "v1.34.3"
          - "v1.33.7"
          - "v1.32.11"
          - "v1.31.14"
          - "v1.30.13"
          - "v1.29.14"
          - "v1.28.15"
          - "v1.27.16"
    env:
      KIND_IMAGE: kindest/node:${{matrix.kind_image}}
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup kind
        run: |
          kind create cluster --image="$KIND_IMAGE" --name test-pgd
      - name: Install cargo-nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - run: cargo fetch --verbose
      - run: cargo nextest run --all --frozen
        timeout-minutes: 10

  tests-result:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

  lint-helm:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: helm lint charts/pod-graceful-drain --strict

  build-image:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          docker build --file docker/build.Dockerfile \
            --tag "localhost/pod-graceful-drain:latest" \
            .
      - run: docker image save --output pod-graceful-drain.tar localhost/pod-graceful-drain
      - uses: actions/upload-artifact@v7
        with:
          name: pod-graceful-drain.tar
          path: ./pod-graceful-drain.tar

  smoke-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind_image:
          - "v1.35.1"
          - "v1.34.3"
          - "v1.33.7"
          - "v1.32.11"
          - "v1.31.14"
          - "v1.30.13"
          - "v1.29.14"
          - "v1.28.15"
          - "v1.27.16"
    env:
      KIND_IMAGE: kindest/node:${{matrix.kind_image}}
    needs:
      - build-image
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - uses: actions/download-artifact@v8
        with:
          name: pod-graceful-drain.tar
      - run: uv sync --frozen
      - name: Smoke test - Setup
        run: |
          docker image load --input pod-graceful-drain.tar
          kind create cluster --image="$KIND_IMAGE" --name test-pgd
          kind load docker-image localhost/pod-graceful-drain:latest --name=test-pgd
          helm install pod-graceful-drain charts/pod-graceful-drain \
            --create-namespace --namespace pod-graceful-drain \
            --set image.repository=localhost/pod-graceful-drain --set image.tag=latest \
            --set replicaCount=1 \
            --set deleteAfter=20s \
            --set experimentalGeneralIngress=true \
            --set logLevel=info\\,pod_graceful_drain=trace\\,pod_graceful_drain::reflector=info \
            --wait=true --timeout=1m
      - name: Smoke test
        run: uv run --frozen pytest -- --capture=tee-sys -n auto
        timeout-minutes: 10

  smoke-tests-result:
    runs-on: ubuntu-latest
    needs: smoke-test
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
