name: Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - run: make test
      - run: helm lint charts/pod-graceful-drain --strict
      - uses: codecov/codecov-action@v1
        with:
          file: ./cover.out